/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Event } from '../models/event';
import { User } from '../models/user';
export interface EventRegistration {
  createdAt?: string;
  event?: Event;
  eventId?: number;
  id?: number;
  updatedAt?: string;
  user?: User;
  userId?: number;
}
